server:
  port: 8088

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
