server:
  port: 8086

spring:
  application:
    name: admin-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    consul:
      enabled: false
  config:
    import: "optional:configserver:"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#spring.security.oauth2.resourceserver.jwt:
#  issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.context.annotation.AnnotationConfigApplicationContext: DEBUG

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
